[build]
  functions = "functions"  # Directory for serverless functions
  publish = "public"       # Directory for static files (if any)
  
[[redirects]]
  from = "/api/*"
  to = "/functions/server"
  status = 200

[dev]
  command = "netlify functions:serve" # Command for local development
  port = 3000 # Port for Netlify Dev Server