[build]
  functions = "functions/" # Or wherever your functions are
  publish = "public/" #  If you have static assets (e.g., a frontend)

[dev]
  framework = "#static" # or your frontend framework if applicable
  command = "npm run start" # if you have a start script